name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Extract Version
      id: extract_version
      run: |
        VERSION=$(grep -oP '(?<=^VERSION=").*?(?=")' entrypoint.sh)
        echo "VERSION=$VERSION"
        echo "version=$VERSION" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          fxtelekom/fxrouter:v${{ env.version }}
          fxtelekom/fxrouter:latest
        platforms: linux/amd64,linux/arm64,linux/arm/v7
